package orm;

import org.apache.ibatis.io.Resources;
import org.apache.ibatis.session.SqlSession;
import org.apache.ibatis.session.SqlSessionFactory;
import org.apache.ibatis.session.SqlSessionFactoryBuilder;

import java.io.IOException;
import java.util.List;

public class Main {
    public static void main(String[] args) throws IOException {
        SqlSessionFactory factory = new SqlSessionFactoryBuilder().build(Resources.getResourceAsStream("mybatis-config.xml"));
        SqlSession sqlSession = factory.openSession();
        // 1) SELECT
        User user = (User) sqlSession.selectOne("orm.UserMapper.getUserById",2);
        System.out.println(user);
        sqlSession.close();

        // 2) INSERT
//        User user = new User();
//        user.setUsername("Boy1");
//        user.setAddress("New York");
//        int insert = sqlSession.insert("orm.UserMapper.addUser",user);
//        System.out.println(insert);
//        sqlSession.commit();
//        sqlSession.close();

        // 3) INSERT with UUID generated by MySQL
//        User user = new User();
//        user.setUsername("Boy2");
//        user.setAddress("Washington");
//        int insert = sqlSession.insert("orm.UserMapper.addUser2", user);
//        System.out.println(insert);
//        sqlSession.commit();
//        sqlSession.close();

//        4) DELETE
//        int delete = sqlSession.delete("orm.UserMapper.deleteUserById","f093a8a8-7fb6-11ea-aa50-000c297bf035");
//        System.out.println(delete);
//        sqlSession.commit();
//        sqlSession.close();

//        5) Update
//          User user = new User();
//          user.setId("3");
//          user.setUsername("new-username");
//          int update = sqlSession.update("orm.UserMapper.updateUser", user);
//          System.out.println(update);
//          sqlSession.commit();
//          sqlSession.close();

//        6) Read
//        List<User> list = sqlSession.selectList("orm.UserMapper.getAllUser");
//        System.out.println(list);
//        sqlSession.commit();
//        sqlSession.close();


    }
}
